# Generated by Django 3.0.3 on 2020-04-25 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20200422_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, to='recipes.Category'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cooktime',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='recipes/static/images/recipe_hero'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='preptime',
            field=models.CharField(max_length=64),
        ),
    ]
