# Generated by Django 3.0.3 on 2020-04-26 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20200425_0012'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='cooktime_initial',
            field=models.CharField(default=0, max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='preptime_initial',
            field=models.CharField(default=0, max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recipe',
            name='category',
            field=models.ManyToManyField(to='recipes.Category'),
        ),
    ]
