# Generated by Django 3.0.3 on 2020-04-30 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_recipelist'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='ingredients_length',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
