# Generated by Django 3.0.3 on 2020-04-30 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_recipe_ingredients_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='custom',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
