# Generated by Django 3.0.3 on 2020-04-30 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_category_custom'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='total_time',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
