# Generated by Django 3.0.3 on 2020-05-03 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0012_auto_20200503_1631'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='inspiration',
        ),
    ]
