# Generated by Django 3.0.3 on 2020-05-04 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0014_recipe_inspiration'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipelist',
            name='public',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
